### ISSUE TITLE
Bind uniform to texunit

### ISSUE THREAD

**Issue by markD9** [marcodiiga/glquad#1]
We should not rely on the driver automatically binding our first uniform to the first texture unit and have a more conservative and portable approach like:

```
glActiveTexture(GL_TEXTURE0);
uniform_loc = glGetUniformLocation(shader_id, "texture_diffuse");
glUniform1i(uniform_loc, 0); // Bind uniform to texture unit 0
```

**Comment by marcodiiga** [comment]
Implemented with 9ed6e0f5e492faadcdc45a81eda7e8098d768813
